<#
.SYNOPSIS
    Compiles Assets/Scripts headlessly WITHOUT opening Unity.

.DESCRIPTION
    Unity only allows one instance per project (Temp/UnityLockfile). While the
    Editor is open, `Unity.exe -batchmode -projectPath <this project>` aborts
    with "another Unity instance is running with this project open" (exit 1).

    So for a fast syntax/API check we reuse the csproj files Unity already
    generated (they carry all ~370 correct assembly references) and rebuild them
    with `dotnet build`, but with the Compile item list replaced by a glob over
    Assets/Scripts so newly added files are picked up before Unity has
    regenerated anything.

    Two projects are generated because editor-only scripts need the editor
    assembly set, which Assembly-CSharp.csproj does not fully provide.

    Note: the runtime project canNOT be used to detect a stray `using
    UnityEditor;` in runtime code -- inside the Editor, Unity compiles
    Assembly-CSharp against UnityEditor too, so such code compiles here and only
    breaks at player build time. A separate source lint below covers that case.

        CompileCheck.Runtime.csproj  <- Assets/Scripts, minus Editor/
        CompileCheck.Editor.csproj   <- Assets/Scripts/**/Editor/**

    Both are written to the project root (where *.csproj is already gitignored
    and where Unity's relative paths resolve) with build output isolated in
    .compilecheck/.

    This is a pre-flight check, not a substitute for Unity. Unity remains the
    authority on whether the project actually compiles.

.EXAMPLE
    pwsh -File tools/compile-check.ps1
#>
[CmdletBinding()]
param(
    [string]$ProjectRoot
)

$ErrorActionPreference = 'Stop'

if (-not $ProjectRoot) {
    # $PSScriptRoot is not reliably populated inside a param() default under
    # Windows PowerShell 5.1, so resolve the script's own location here instead.
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    $ProjectRoot = Split-Path -Parent $scriptDir
}

$ProjectRoot = (Resolve-Path $ProjectRoot).Path
Set-Location $ProjectRoot

$outDir = Join-Path $ProjectRoot '.compilecheck'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

function New-CheckProject {
    param(
        [string]$SourceCsproj,
        [string]$TargetCsproj,
        [string]$Include,
        [string]$Exclude,
        [string]$Tag
    )

    if (-not (Test-Path $SourceCsproj)) {
        throw "Missing $SourceCsproj. Open the project in Unity once so it regenerates the csproj files."
    }

    $doc = [xml](Get-Content -Raw $SourceCsproj)
    $root = $doc.DocumentElement

    # Drop Unity's hard-coded Compile list; we substitute a glob below.
    foreach ($node in @($doc.SelectNodes('//Compile'))) {
        $null = $node.ParentNode.RemoveChild($node)
    }

    # Retarget the ProjectReference so the Editor check compiles against OUR
    # runtime check project, not Unity's (stale) Assembly-CSharp.csproj.
    foreach ($node in @($doc.SelectNodes("//ProjectReference[@Include='Assembly-CSharp.csproj']"))) {
        $node.SetAttribute('Include', 'CompileCheck.Runtime.csproj')
    }

    # csc fails with "no inputs specified" on an empty source set, and the glob
    # is legitimately empty until the first script lands. Keep a placeholder.
    $stub = Join-Path $outDir "_Stub.$Tag.cs"
    Set-Content -Path $stub -Encoding UTF8 -Value @"
// Generated by tools/compile-check.ps1 -- keeps the compiler happy when the
// source glob is empty. Not part of the Unity project (.compilecheck is outside
// Assets/, so Unity never sees it).
namespace CompileCheck { internal static class Stub$Tag { } }
"@

    $ig = $doc.CreateElement('ItemGroup')
    $c = $doc.CreateElement('Compile')
    $c.SetAttribute('Include', $Include)
    if ($Exclude) { $c.SetAttribute('Exclude', $Exclude) }
    $null = $ig.AppendChild($c)
    $s = $doc.CreateElement('Compile')
    $s.SetAttribute('Include', ".compilecheck\_Stub.$Tag.cs")
    $null = $ig.AppendChild($s)
    $null = $root.AppendChild($ig)

    # Keep build artifacts out of Unity's Temp/ and Library/.
    #
    # These must be rewritten IN PLACE rather than appended: MSBuild computes
    # TargetPath while importing Sdk.targets, so a PropertyGroup added after that
    # import is evaluated too late to redirect anything (and warns MSB3539).
    # Unity declares all of these in the first PropertyGroup, ahead of the
    # Sdk.props import, which is exactly where they need to stay.
    $paths = @{
        'BaseIntermediateOutputPath' = ".compilecheck\obj\$Tag\"
        'IntermediateOutputPath'     = ".compilecheck\obj\$Tag\"
        'OutputPath'                 = ".compilecheck\bin\$Tag\"
        'UseCommonOutputDirectory'   = 'false'
    }
    foreach ($key in @($paths.Keys)) {
        $existing = @($doc.SelectNodes("//$key"))
        if ($existing.Count -gt 0) {
            foreach ($node in $existing) { $node.InnerText = $paths[$key] }
        } else {
            # Not declared by Unity: add it to the first PropertyGroup, which
            # sits before the Sdk.props import.
            $e = $doc.CreateElement($key)
            $e.InnerText = $paths[$key]
            $null = $doc.SelectSingleNode('//PropertyGroup').AppendChild($e)
        }
    }

    $doc.Save($TargetCsproj)
}

# The generated csproj files MUST sit at the project root: Unity's originals use
# paths relative to the root (Compile items, Sdk imports, ProjectReference), and
# MSBuild resolves those relative to the csproj's own directory.
$runtimeProj = Join-Path $ProjectRoot 'CompileCheck.Runtime.csproj'
$editorProj  = Join-Path $ProjectRoot 'CompileCheck.Editor.csproj'

# A folder that owns an .asmdef compiles as its OWN assembly, and Unity's csproj
# files already pull that assembly in by reference. Globbing its sources in as
# well would define every one of its types twice -- tolerable in the runtime
# project (CS0436: the source copy wins) but a hard ambiguity ERROR in the editor
# one (CS0433), which failed the whole check for anything touching the quiz.
# Those assemblies are still compiled, via their own project references.
function Get-AsmdefExcludes {
    param([string]$Root)

    $excludes = @()
    $scripts = Join-Path $Root 'Assets/Scripts'

    foreach ($asmdef in Get-ChildItem -Path $scripts -Filter '*.asmdef' -Recurse -File) {
        $relative = $asmdef.Directory.FullName.Substring($Root.Length).TrimStart([char]92, [char]47)
        $excludes += (Join-Path $relative '**\*.cs')
    }

    return $excludes
}

$asmdefExcludes = Get-AsmdefExcludes -Root $ProjectRoot

New-CheckProject -SourceCsproj 'Assembly-CSharp.csproj' -TargetCsproj $runtimeProj `
    -Include 'Assets\Scripts\**\*.cs' `
    -Exclude ((@('Assets\Scripts\**\Editor\**\*.cs') + $asmdefExcludes) -join ';') -Tag 'Runtime'

New-CheckProject -SourceCsproj 'Assembly-CSharp-Editor.csproj' -TargetCsproj $editorProj `
    -Include 'Assets\Scripts\**\Editor\**\*.cs' -Exclude ($asmdefExcludes -join ';') -Tag 'Editor'

# Building the Editor project pulls in the Runtime project via ProjectReference,
# so one invocation checks both.
Write-Host "compile-check: building Assets/Scripts (runtime + editor)..." -ForegroundColor Cyan
& dotnet build $editorProj -v m -nologo --property:WarningLevel=4
$code = $LASTEXITCODE

# Editor-only API used from runtime code compiles fine in the Editor and then
# fails the player build. The compiler cannot catch it here, so lint the source.
$leaks = @()
$runtimeFiles = Get-ChildItem -Path 'Assets/Scripts' -Filter '*.cs' -Recurse -File |
    Where-Object { $_.FullName.Split(@([char]47, [char]92)) -notcontains 'Editor' }

foreach ($file in $runtimeFiles) {
    $text = Get-Content -Raw $file.FullName
    if ($text -match 'UnityEditor' -and $text -notmatch '#if\s+UNITY_EDITOR') {
        $leaks += $file.FullName
    }
}

if ($leaks.Count -gt 0) {
    Write-Host "compile-check: editor API referenced from runtime code (guard it with #if UNITY_EDITOR, or move the file into an Editor/ folder):" -ForegroundColor Red
    foreach ($leak in $leaks) { Write-Host "    $leak" -ForegroundColor Red }
    $code = 1
}

if ($code -eq 0) {
    Write-Host "compile-check: OK" -ForegroundColor Green
} else {
    Write-Host "compile-check: FAILED (exit $code)" -ForegroundColor Red
}
exit $code
